spring.application.name=stagepass

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/stagepass
spring.datasource.username=username=your_username
spring.datasource.password=password=your_password

server.port=8080

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true


# Initialize data
spring.sql.init.mode=always
